name: check_projection
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: eugene.kot <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4
